### ISSUE TITLE
Bug: Fixing the login/ register issue 

### ISSUE THREAD

**Issue by ameyakhyati** [Sanchitbajaj02/palettegram#300]
### What happened?

I tried login-in to the website and it gave me errors - 
1. Same name, email ID already exists
2. Cannot create a session while another session is active but no session being displayed even after refreshing many times 

### Add screenshots

![Palettegram](https://github.com/Sanchitbajaj02/palettegram/assets/73154768/f0fe4a50-5d92-4333-a25f-1b5174623c50)

### What browsers are you seeing the problem on?

Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
> I tried login-in to the website and it gave me errors -

If you have once created your account, a session is created in cookies for the same so you can't re-register unless and until that is cleared. Although it seems like an error but it is the general flow according to Appwrite. 

If you have a better suggestion on how to streamline this functionality, please propose otherwise I will mark it as close

**Comment by ameyakhyati** [comment]
The thing is i tried login - in too thinking that my account is created but going to the login section it sent me the message no account found and i need to register

**Comment by Sanchitbajaj02** [comment]
You can go through the codebase but I don't think there is an issue. If you find any key component, please raise here or in Discord

**Comment by ameyakhyati** [comment]
Okiee :)

**Comment by Stiffpixels** [comment]
this issue occurred with me as well.

**Comment by Sanchitbajaj02** [comment]
Hi @ameyakhyati 
What's the status of this issue?

**Comment by Sanchitbajaj02** [comment]
Yeah sure, you can take your time, it's just that to update me on this ticket accordingly

**Comment by ameyakhyati** [comment]
okie thank you very much :)

**Comment by ArtiGaund** [comment]
Previously application was supporting old version of appwrite, that's why method written in auth api file was working fine. But someone might have upgraded the appwrite, so package.json contains upgraded version of appwrite. Appwrite have different methods for latest version. It's doesn't support createEmailSession() method, but support createEmailAndPasswordSession() and updateRecovery() have 3 parameters not 4 in upgraded appwrite. After these 2 modification application is working fine for me.

**Comment by Sanchitbajaj02** [comment]
> Appwrite have different methods for latest version. It's doesn't support createEmailSession() method, but support createEmailAndPasswordSession() and updateRecovery() have 3 parameters not 4 in upgraded appwrite. After these 2 modification application is working fine for me.

If I remember correctly, I have removed the dependency updation in package.json so that it will be version locked

**Comment by Sanchitbajaj02** [comment]
> my appwrite version is 14 and master branch on the repo is 13. But its working in my system. May be if you locked the version and someone made some modification, which is only supported by latest version of the app

Ohh, thanks for the update. I think we can close this issue then? What's your call?

**Comment by ArtiGaund** [comment]
If issue is resolved then close it. This issue was not raised by me.

**Comment by ameyakhyati** [comment]
@Sanchitbajaj02  I sincerely apologize for being inactive and no updating you regarding the issue.
