### ISSUE TITLE
Feat: Share Profile

### ISSUE THREAD

**Issue by Sid-80** [Sanchitbajaj02/palettegram#377]
### What feature?

There is no option for sharing profile!

I am willing to add this enhancement under GSSOC24

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/101277141/bfafa533-b44f-4fbf-9a2a-30a011cb2a5a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by yashd-dev** [comment]
Hi, this sounds great! How do you plan on implementing it?

**Comment by Sid-80** [comment]
![image](https://github.com/Sanchitbajaj02/palettegram/assets/101277141/129556f2-d956-4a4f-bc97-487305f472c6)

Each user contains a unique id, by using dynamic routing we can implement this feature!

**Comment by yashd-dev** [comment]
Instead of dynamic routing, if you look at the component for that page, the userID is getting extracted from the cookie as well. Another addition I can think of is using the [Navigator API](https://developer.mozilla.org/en-US/docs/Web/API/Window/navigator) you can copy to the clipboard on PC and [Web Share API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API) on mobile devices

**Comment by Sid-80** [comment]
@yashd-dev Yepp! Thought of using modal

**Comment by Sid-80** [comment]
@yashd-dev https://github.com/Sanchitbajaj02/palettegram/pull/381 Please review!
