### ISSUE TITLE
Bug: Feed blending with navbar

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#58]
### What happened?

Contents of the feed page is blending with the navbar. It might be due to the z-index of some components.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/54807565-4058-43cb-8e56-178e75f6a777)

### What browsers are you seeing the problem on?

Microsoft Edge, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
@ricgomez99 currently no one is working on this issue, you can work on it

**Comment by ricgomez99** [comment]
@Sanchitbajaj02  Ok Thanks!! I'll keep you up to date with the changes.

**Comment by ricgomez99** [comment]
@Sanchitbajaj02 By any chance, do you have a test account that I can use to login to the page?

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 By any chance, do you have a test account that I can use to login to the page?

Currently the prod and dev are on same account. 
But I will make them seperate by tomorrow and it will be available in the discord server, so make sure to join.

**Comment by ricgomez99** [comment]
Okay, perfect! I'll take a look at it tomorrow then.

**Comment by irfanfaraaz** [comment]
Just comment out few blocks of code from middleware.ts then you will be able to login

**Comment by Sanchitbajaj02** [comment]
> Just comment out few blocks of code from middleware.ts then you will be able to access private routes

It is one of the approaches for now, but not the good one. @ricgomez99 you can do this if you want to.

**Comment by ricgomez99** [comment]
@Sanchitbajaj02 No problem! what blocks of code should I comment out?

**Comment by ricgomez99** [comment]
@irfanfaraaz Perfect, thank you!

**Comment by ricgomez99** [comment]
@Sanchitbajaj02  @irfanfaraaz  Hey guys! I'm still working on the navbar issue, and I just wanted to ask you something about the navbar component, its position should always be sticky?? I think that's making the element overlap the main content when you scroll down on the feed page. Please let me know if it must be the position attribute for that navbar. Cheers!

**Comment by Sanchitbajaj02** [comment]
Actually the navbar will act like quick action for the users, like if they want to go to settings or any other tabs, that's why I made it sticky in the first place.
I think instead of changing the z-index of different components, what you can do is try giving the color on light as well as on dark them. Maybe that will solve that.

**Comment by ricgomez99** [comment]
Got ya, I will try that instead!

**Comment by ricgomez99** [comment]
@Sanchitbajaj02 @irfanfaraaz Hey guys!! I've been working on a solution for the navbar issue we've been facing. Instead of applying a distinct color to separate it from the main content, I've introduced a subtle but effective change. I applied a backdrop blur effect to the navbar element and adjusted the z-index to ensure it remains distinct from the elements in the background, considering the navbar has a sticky property.

I'd love to hear your thoughts on this approach before creating a PR. Do you agree with this solution, or do you have any alternative suggestions? 
I recorded a video to show you all the changes I made. To be able to scroll down, I just copied and pasted the copyright section (only in the browser previewer).
Looking forward to your input.

https://www.loom.com/share/b2af149c691340a88bc4ce4f79eb0806?sid=920b875e-3da8-4dac-9446-a4a820c33400

**Comment by ricgomez99** [comment]
@Sanchitbajaj02 No problem! I'll do it right away
